github: [octocat, anotheruser]
patreon: creatorname
open_collective: collectiveusername
ko_fi: coffeeuser
tidelift: npm/express
community_bridge: kubernetes
liberapay: liberapayuser
issuehunt: huntuser
lfx_crowdfunding: openjs
polar: polaruser
buy_me_a_coffee: coffeeusername
custom: ['https://example.com/support', 'https://anotherexample.com/donate'
